export const FETCH_AMOUNT_SEND           = 'FETCH_AMOUNT_SEND';
export const FETCH_AMOUNT_SEND_SUCCESS   = 'FETCH_AMOUNT_SEND_SUCCESS';
export const FETCH_AMOUNT_SEND_ERROR     = 'FETCH_AMOUNT_SEND_ERROR';

export const FETCH_AMOUNT_RECEIVE           = 'FETCH_AMOUNT_RECEIVE';
export const FETCH_AMOUNT_RECEIVE_SUCCESS   = 'FETCH_AMOUNT_RECEIVE_SUCCESS';
export const FETCH_AMOUNT_RECEIVE_ERROR     = 'FETCH_AMOUNT_RECEIVE_ERROR';

export const FETCH_LOADER_OPEN      = 'FETCH_LOADER_OPEN';
export const FETCH_LOADER_CLOSE     = 'FETCH_LOADER_CLOSE';
export const FETCH_LOADER_ERROR     = 'FETCH_LOADER_ERROR';

export const FETCH_MODAL_OPEN      = 'FETCH_MODAL_OPEN';
export const FETCH_MODAL_CLOSE     = 'FETCH_MODAL_CLOSE';
export const FETCH_MODAL_ERROR     = 'FETCH_MODAL_ERROR';

export const FETCH_ORDER           = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCESS   = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_ERROR     = 'FETCH_ORDER_ERROR';

export const FETCH_CUSTOMER           = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMER_SUCCESS   = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_ERROR     = 'FETCH_CUSTOMER_ERROR';

export const BANK_SEND              = 'BANK_SEND';
export const BANK_SEND_SUCCESS      = 'BANK_SEND_SUCCESS';
export const BANK_SEND_ERROR        = 'BANK_SEND_ERROR';

export const BANK_RECEIVE           = 'BANK_RECEIVE';
export const BANK_RECEIVE_SUCCESS   = 'BANK_RECEIVE_SUCCESS';
export const BANK_RECEIVE_ERROR     = 'BANK_RECEIVE_ERROR';

export const FETCH_EXCHANGE           = 'FETCH_EXCHANGE';
export const FETCH_EXCHANGE_SUCCESS   = 'FETCH_EXCHANGE_SUCCESS';
export const FETCH_EXCHANGE_ERROR     = 'FETCH_EXCHANGE_ERROR';

export const FETCH_TAX           = 'FETCH_TAX';
export const FETCH_TAX_SUCCESS   = 'FETCH_TAX_SUCCESS';
export const FETCH_TAX_ERROR     = 'FETCH_TAX_ERROR';

export const FETCH_USER_STATUS           = 'FETCH_USER_STATUS';
export const FETCH_USER_STATUS_SUCCESS   = 'FETCH_USER_STATUS_SUCCESS';
export const FETCH_USER_STATUS_ERROR     = 'FETCH_USER_STATUS_ERROR';
